name: Deploy to cloud function

on:
  push:
    branches:
      - main

jobs:
  deploy_cloud_function:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'googlefitauth'
        entry_point: 'execute'
        runtime: 'python39'
        region: 'europe-west2'
        env_vars: 'GOOGLE_FIT_REDIRECT_HOST=europe-west2-elevated-apex-308311.cloudfunctions.net,GOOGLE_FIT_CLIENT_ID=857227057976-csoa4f8q00qots6ir53vc58ha0fqljvl.apps.googleusercontent.com,GOOGLE_FIT_CLIENT_SECRET=${{ secrets.GOOGLE_FIT_CLIENT_SECRET }}'
